if (! this.sh_languages) {
  this.sh_languages = {};
}
sh_languages['gherkin_fr'] = [
  [
    [
      /#/g,
      'sh_comment',
      1
    ],
    [
      /\b[+-]?(?:(?:0x[A-Fa-f0-9]+)|(?:(?:[\d]*\.)?[\d]+(?:[eE][+-]?[\d]+)?))u?(?:(?:int(?:8|16|32|64))|L)?\b/g,
      'sh_number',
      -1
    ],
    [
      /^(?:[\s]*(?:Mais |Et |Alors |Lorsqu|Lorsque |Quand |Étant données |Étant donnés |Étant donnée |Étant donné |Etant données |Etant donnés |Etant donnée |Etant donné |Soit |\* |Exemples|Plan du Scénario|Plan du scénario|Scénario|Contexte|Fonctionnalité))/g,
      'sh_keyword',
      -1
    ],
    [
      /^(?:[\s]*'(?:[^\\']|\\.)*'[\s]*|[\s]*\"(?:[^\\\"]|\\.)*\"[\s]*)$/g,
      'sh_comment',
      -1
    ],
    [
      /(?:[\s]*'{3})/g,
      'sh_string',
      2
    ],
    [
      /(?:[\s]*\"{3})/g,
      'sh_string',
      3
    ],
    [
      /"/g,
      'sh_string',
      4
    ],
    [
      /'/g,
      'sh_string',
      5
    ],
    [
      /(?:@[^@\r\n\t ]+)/g,
      'sh_type',
      -1
    ],
    [
      /\|/g,
      'sh_symbol',
      -1
    ]
  ],
  [
    [
      /$/g,
      null,
      -2
    ]
  ],
  [
    [
      /(?:'{3})/g,
      'sh_string',
      -2
    ]
  ],
  [
    [
      /(?:\"{3})/g,
      'sh_string',
      -2
    ]
  ],
  [
    [
      /$/g,
      null,
      -2
    ],
    [
      /\\(?:\\|")/g,
      null,
      -1
    ],
    [
      /"/g,
      'sh_string',
      -2
    ]
  ],
  [
    [
      /$/g,
      null,
      -2
    ],
    [
      /\\(?:\\|')/g,
      null,
      -1
    ],
    [
      /'/g,
      'sh_string',
      -2
    ]
  ]
];
